project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - "index.qmd"
    - "analyses/*.qmd" # render these manually as time-consuming to run
    - "eda/*.qmd"

website:
  sidebar:
    title: ASCOT Antiviral Analyses
    style: "floating"
    search: true
    align: left
    contents:
      - text: "Summary"
        file: index.qmd
      - section: "Overview and Baseline"
        contents:
          - eda/data-explore.qmd
          - eda/patient-disposition.qmd
          - eda/baseline.qmd
          - eda/adherence.qmd
          - eda/safety-listings.qmd
      - section: "Outcomes and Analyses"
        contents:
          - "analyses/6-0_primary_outcome.qmd"
          - "analyses/7-1_time_to_clinical_recovery.qmd"
          - "analyses/7-2_who_ordinal_scale.qmd"
          - "analyses/7-3_all_cause_mortality.qmd"
          - "analyses/7-4_days_alive_and_hospital_free.qmd"
          - "analyses/7-5_days_alive_ventilation_free.qmd"
          - "analyses/7-6_shortness_of_breath.qmd"
          - "analyses/7-7_breathlessness.qmd"
          - "analyses/8_antiviral_specific.qmd"

format:
  html:
    toc: true
    toc-depth: 3
    toc-location: right
    fig-align: center
    captions: true
    cap-location: margin
    table-captions: true
    tbl-cap-location: margin
    reference-location: margin
    theme: litera
    fontsize: 1em
    max-width: "2000px"
    self-contained: true
    standalone: true
    code-tools: true
    code-fold: true
    code-link: false

execute:
  warning: false
  message: false
  echo: true
  freeze: auto

engine: knitr
